In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b=np.asarray([1,2,3,4])

In [5]:
b

array([1, 2, 3, 4])

In [6]:
c=np.asanyarray([1,2,3,4])

In [7]:
c

array([1, 2, 3, 4])

In [8]:
d=np.copy(a)

In [9]:
d

array([1, 2, 3, 4])

In [10]:
d.ndim

1

In [11]:
ar=np.zeros((3,4))

In [12]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ar=np.ones((3,4))

In [14]:
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
ar=np.arange(1.3,25.4,2)

In [20]:
ar

array([ 1.3,  3.3,  5.3,  7.3,  9.3, 11.3, 13.3, 15.3, 17.3, 19.3, 21.3,
       23.3, 25.3])

In [21]:
ar=np.linspace(2,6,20)

In [22]:
ar

array([2.        , 2.21052632, 2.42105263, 2.63157895, 2.84210526,
       3.05263158, 3.26315789, 3.47368421, 3.68421053, 3.89473684,
       4.10526316, 4.31578947, 4.52631579, 4.73684211, 4.94736842,
       5.15789474, 5.36842105, 5.57894737, 5.78947368, 6.        ])

In [31]:
ar=np.logspace(2,6,20)

In [32]:
ar

array([1.00000000e+02, 1.62377674e+02, 2.63665090e+02, 4.28133240e+02,
       6.95192796e+02, 1.12883789e+03, 1.83298071e+03, 2.97635144e+03,
       4.83293024e+03, 7.84759970e+03, 1.27427499e+04, 2.06913808e+04,
       3.35981829e+04, 5.45559478e+04, 8.85866790e+04, 1.43844989e+05,
       2.33572147e+05, 3.79269019e+05, 6.15848211e+05, 1.00000000e+06])

In [25]:
a=np.full((3,4),66)

In [26]:
a

array([[66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66]])

In [29]:
a=np.eye(3,4)

In [30]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
arr=np.random.randn(3,4)

In [36]:
arr

array([[ 0.27747608,  1.96881668,  2.41324152,  0.14208941],
       [ 0.48888852, -0.48955419, -1.42633439,  0.70378029],
       [-1.2404268 , -0.70727837, -0.7755059 ,  0.03137481]])

In [37]:
np.random.rand(3,4)

array([[0.84898218, 0.17133644, 0.15654941, 0.47734501],
       [0.34077355, 0.65977008, 0.79308551, 0.85031059],
       [0.78292575, 0.41290311, 0.83555686, 0.08420772]])

In [95]:
arr=np.random.randint(1,50,(3,4))
arr

array([[46, 24, 25, 25],
       [39, 41, 40,  2],
       [12, 11,  2,  2]])

In [96]:
arr.size

12

In [42]:
arr.shape

(3, 4)

In [43]:
arr.reshape(6,-22345)

array([[25, 20],
       [49,  8],
       [24, 16],
       [30, 29],
       [42, 42],
       [ 5, 35]])

In [45]:
b=arr.flatten()

In [46]:
b

array([25, 20, 49,  8, 24, 16, 30, 29, 42, 42,  5, 35])

In [47]:
np.expand_dims(b,axis=1)

array([[25],
       [20],
       [49],
       [ 8],
       [24],
       [16],
       [30],
       [29],
       [42],
       [42],
       [ 5],
       [35]])

In [48]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [86]:
arr1=np.random.randint(1,50,(3,4))
arr2=np.random.randint(1,50,(3,4))

In [88]:
arr1&arr2

array([[ 0,  8, 10, 11],
       [24,  7, 32, 32],
       [27,  9, 12,  3]])

In [50]:
arr1+arr2

array([[47, 61, 38, 16],
       [11, 58, 92, 76],
       [62, 62, 72, 53]])

In [51]:
arr1-arr2

array([[-23,   5,  24, -14],
       [ -9, -38,  -6, -18],
       [ -4,  -8,   8, -43]])

In [52]:
arr1*arr2

array([[ 420,  924,  217,   15],
       [  10,  480, 2107, 1363],
       [ 957,  945, 1280,  240]])

In [54]:
arr1/arr2

array([[0.34285714, 1.17857143, 4.42857143, 0.06666667],
       [0.1       , 0.20833333, 0.87755102, 0.61702128],
       [0.87878788, 0.77142857, 1.25      , 0.10416667]])

In [55]:
arr1%arr2

array([[12,  5,  3,  1],
       [ 1, 10, 43, 29],
       [29, 27,  8,  5]])

In [56]:
arr1**arr2

array([[          0,  -702813311,  1742810335,           1],
       [          1,           0,    -5721877,  -455304971],
       [ 2104252573, -1304768669,           0, -1322549439]])

In [82]:
arr1=np.random.randint(1,50,(3,4))
arr1

array([[10,  7, 34, 41],
       [32,  2, 39, 24],
       [42, 26, 35, 15]])

In [63]:
np.sum(arr1)

278

In [64]:
np.min(arr1)

3

In [65]:
np.sqrt(arr1)

array([[6.78232998, 4.24264069, 6.55743852, 1.73205081],
       [5.91607978, 6.        , 2.44948974, 5.        ],
       [6.78232998, 2.        , 2.82842712, 2.82842712]])

In [66]:
np.power(arr1,2)

array([[2116,  324, 1849,    9],
       [1225, 1296,   36,  625],
       [2116,   16,   64,   64]], dtype=int32)

In [67]:
np.max(arr1)

46

In [68]:
np.cumsum(arr1)

array([ 46,  64, 107, 110, 145, 181, 187, 212, 258, 262, 270, 278])

In [69]:
np.std(arr1)

16.58228639911343

In [70]:
np.var(arr1)

274.97222222222223

In [72]:
np.median(arr1)

21.5

In [73]:
np.sin(arr1)

array([[ 0.90178835, -0.75098725, -0.83177474,  0.14112001],
       [-0.42818267, -0.99177885, -0.2794155 , -0.13235175],
       [ 0.90178835, -0.7568025 ,  0.98935825,  0.98935825]])

In [74]:
np.cos(arr1)

array([[-0.43217794,  0.66031671,  0.5551133 , -0.9899925 ],
       [-0.90369221, -0.12796369,  0.96017029,  0.99120281],
       [-0.43217794, -0.65364362, -0.14550003, -0.14550003]])

In [75]:
np.sinh(arr1)

array([[4.74805971e+19, 3.28299846e+07, 2.36391973e+18, 1.00178749e+01],
       [7.93006726e+14, 2.15561577e+15, 2.01713157e+02, 3.60024497e+10],
       [4.74805971e+19, 2.72899172e+01, 1.49047883e+03, 1.49047883e+03]])

In [76]:
np.tanh(arr1)

array([[1.        , 1.        , 1.        , 0.99505475],
       [1.        , 1.        , 0.99998771, 1.        ],
       [1.        , 0.9993293 , 0.99999977, 0.99999977]])

In [77]:
np.log10(arr1)

array([[1.66275783, 1.25527251, 1.63346846, 0.47712125],
       [1.54406804, 1.5563025 , 0.77815125, 1.39794001],
       [1.66275783, 0.60205999, 0.90308999, 0.90308999]])

In [78]:
arr1.sort(axis=0)

In [84]:
np.exp(arr1)

array([[2.20264658e+04, 1.09663316e+03, 5.83461743e+14, 6.39843494e+17],
       [7.89629602e+13, 7.38905610e+00, 8.65934004e+16, 2.64891221e+10],
       [1.73927494e+18, 1.95729609e+11, 1.58601345e+15, 3.26901737e+06]])

In [79]:
arr1

array([[35,  4,  6,  3],
       [46, 18,  8,  8],
       [46, 36, 43, 25]])

In [81]:
arr1.transpose()


array([[35, 46, 46],
       [ 4, 18, 36],
       [ 6,  8, 43],
       [ 3,  8, 25]])

In [93]:
x=np.array([1,2,3,4,56,6,7,8])

In [94]:
np.repeat(x,3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4, 56, 56, 56,  6,  6,
        6,  7,  7,  7,  8,  8,  8])