<a href="https://colab.research.google.com/github/yashsahu27420/PWAssignment/blob/main/Numpy_Basic_Assignment_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Q1 Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))



Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [8]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
for elem in list_:
    print("Data type of element in list_:", type(elem))
for elem in array_list:
    print("Data type of element in array_list:", type(elem))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [3]:
# Q3  Considering the following changes in the variable, array_list:
array_list = np.array(object=list_, dtype=int)
for elem in list_:
    print("Data type of element in list_:", type(elem))
for elem in array_list:
    print("Data type of element in array_list:", type(elem))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [4]:

# Q4. Write a code to find the following characteristics of variable, num_array:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:

# Q5  Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
zeros_array = np.zeros((3, 3))
print("Zeros array:")
print(zeros_array)


Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
identity_matrix = np.eye(5)
print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
